### ISSUE TITLE
[TECH] Use @Constant to be agnostic from env variable

### ISSUE THREAD

**Issue by Romakita** [EmilienLeroy/HighScore#10]
https://github.com/EmilienLeroy/HighScore/blob/20c5d0d53200303b62ab125fa76186999678e8eb/src/home/HomeService.ts#L7

Ts.ED provide you a way to pick variables from global configuration to consume in an injectable service.
This solution is pretty useful for testing and to not depend directly on your code where the settings come from (env variables).

Here the suggestion:

```typescript
@Service()
export class HomeService {
   @Constant('highscore.downoalUrls', '')
   private downloadUrls: Record<string, string>;


  public getDownloadLink(os?: string) {
     return this.downloadUrls[os?.toLowerCase() || 'default'] || this.downloadUrls.default
  }
}
```
In you Server.ts:

```typescript
@Configuration({
   highscore: {
      downloadUrls: {
         default: envs.HIGHSCORE_DOWNLOAD_URL;
         android: envs.HIGHSCORE_ANDROID_DOWNLOAD_URL;
         ios: envs.HIGHSCORE_IOS_DOWNLOAD_URL;
         windows: envs.HIGHSCORE_WINDOWS_DOWNLOAD_URL;
         linux: envs.HIGHSCORE_LINUX_DOWNLOAD_URL;
         macos: envs.HIGHSCORE_MACOS_DOWNLOAD_URL;
      }
   }
}
```

In your test:

```ts

describe('HomeService', () => {
   beforeEach(() => PlatformTest.create({
      highscore: {
         downloadUrls: {
            default: "/default/url",
            ios: "/ios/url"
         }
      }
   }))
   afterEach(() => PlatformTest.reset())
   
  it("should return the expected url depending on the given os", () => {
    const service = PlatformTest.get<HomeService>(HomeService);

     expect(servivce.getDownloadLink()).toEqual('/default/url')
     expect(servivce.getDownloadLink("ios")).toEqual('/ios/url')
     expect(servivce.getDownloadLink("unknown")).toEqual('/default/url')
  })
})
```

Using `@Constant` you can test easily your code and manage your envs variable on /config directory (only one place).

See you
Romain

**Comment by Romakita** [comment]
Base on my previous example, you can refactor your inject middleware ;) (move middleware at the right place, and mode envs in /config)

https://github.com/EmilienLeroy/HighScore/blob/main/src/config/envs/inject.ts

**Comment by EmilienLeroy** [comment]
Hi @Romakita,
Thank you for all the suggestions to improve this project. 
I will try to implement them before the next release. ;)
