### ISSUE TITLE
Port mismatch between documentation and installation instructions

### ISSUE THREAD

**Issue by felleg** [EmilienLeroy/HighScore#12]
Hello! Thanks for this wonderful project, I have been looking for something like this for a long time.

Something I noticed when reading the doc and testing, there seems to be a mismatch between the port used in the documentation commands and the installation instructions. This makes it harder for users to simply copy/paste and use code. I would suggest choosing between 8081 or 8083 as the default port and using that value everywhere.

![image](https://github.com/EmilienLeroy/HighScore/assets/7781739/7d70f61e-c0af-4592-be9a-27d42ec68e05)

**Comment by EmilienLeroy** [comment]
Hi @felleg 
Thank you for your interest in this project!
Yes, the default configuration used by [TsED](https://tsed.io/), the framework used in this project, sets the port to `8083` in the app and `8081` in the Docker configuration.
- [Server.ts#L17](https://github.com/tsedio/tsed-getting-started/blob/master/src/Server.ts#L17)
- [docker-compose.yml](https://github.com/tsedio/tsed-getting-started/blob/master/docker-compose.yml)

However, I believe it would be beneficial to update the documentation to reflect the port `8081` and to update the default port to `8081` as well. If you'd like, you can open a pull request to make these changes.

**Comment by felleg** [comment]
I have started a pull request here for your convenience: https://github.com/EmilienLeroy/HighScore/pull/13

In the hopes that my modifications are accurate. :)

**Comment by EmilienLeroy** [comment]
@felleg 
I've just released a [new version](https://github.com/EmilienLeroy/HighScore/releases/tag/v0.4.2), and the documentation should be much better now. 
Thank you for your contribution! 😄

**Comment by felleg** [comment]
Marvelous! Thank you!
