### ISSUE TITLE
[TECH] All unexpected error from ScoreService are always caught as InternalError

### ISSUE THREAD

**Issue by Romakita** [EmilienLeroy/HighScore#8]
https://github.com/EmilienLeroy/HighScore/blob/20c5d0d53200303b62ab125fa76186999678e8eb/src/scores/ScoreController.ts#L96

All unexpected error from ScoreService are always caught as InternalError. So you don't need in the ScoreController to catch and transform them to an InternalServerError. 

But if you don't won't to have a Mongoose raw error in the error response, you can use exception filter to handle all Mongoose error:

```ts
@Catch("MongooseError", "MongoError")
export class MongooseErrorFilter extends ErrorFilter {
  catch(error: Error, ctx: BaseContext) {
    return super.catch(new InternaleServerError(error.message, error), ctx); // you can adapt the message
  }
}
```

**Comment by EmilienLeroy** [comment]
Closed with #11
